version: 2
jobs:
   build:
     docker:
       - image: totallymoney/circleci-elm-compile

     steps:
       - checkout
       - run: apt-get update && apt-get install -y awscli
       - run:
           name: Build Airplane app
           command: cd airplane && ./build.sh
       - deploy:
           command: |
             cd airplane
             aws s3 cp index.html s3://airplane-toy-app/

             for file in target audios images; do
               aws s3 cp $file s3://airplane-toy-app/$file --recursive
             done
