version: 2
jobs:
   build:
     docker:
       - image: totallymoney/circleci-elm-compile

     steps:
       - checkout
       - run:
           name: Build Airplane app
           command: cd airplane && ./build.sh
